// <auto-generated />
using System;
using LibrosVentaAspnet5.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LibrosVentaAspnet5.Migrations
{
    [DbContext(typeof(TodoContext))]
    [Migration("20201221092149_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("LibrosVentaAspnet5.Models.Cliente", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<long?>("LibroId")
                        .HasColumnType("bigint");

                    b.Property<long>("Nombre")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("LibroId");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("LibrosVentaAspnet5.Models.Libro", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<long>("Nombre")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Libros");
                });

            modelBuilder.Entity("LibrosVentaAspnet5.Models.Cliente", b =>
                {
                    b.HasOne("LibrosVentaAspnet5.Models.Libro", "Libro")
                        .WithMany()
                        .HasForeignKey("LibroId");

                    b.Navigation("Libro");
                });
#pragma warning restore 612, 618
        }
    }
}
